// Generated by CoffeeScript 1.5.0
(function() {

  require.config({
  	baseUrl: '../',
    paths: {
    	//LetDooJs Paths
    	Render : "letdoojs/scripts/Render",
    	Controller : "letdoojs/scripts/Controller",

    	//Librairies Paths
    	domReady : "lib/domReady",
    	jquery : "http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min",
    	Mustache : "lib/mustache"
    }
  });

  require([
  	"domReady",
  	"jquery",
  	"Render",
  	"Controller"
  	],
  	function(domReady,$,Render,Controller) {
      domReady(function () {
      	//loadRoot
      	//loadConfig
      	//ImportCSS LETDOOJS


          Controller.defineController ('testController' , {

              testaction : function () {
                alert("testaction");
              }


          })

          var d = Controller.controllerdefined["testController"];
          d.testaction();



  	 });
  });

})();
