// Generated by CoffeeScript 1.5.0
(function() {

	require.config({
		baseUrl :  Environnement.getPath() ,
		paths : {
			//LetDooJs Paths
			Render : "letdoojs/scripts/Render",
			Controller : "letdoojs/scripts/Controller",
			Router : "letdoojs/scripts/Router",
			Process : "letdoojs/scripts/Process",
			routing : "app/routing",

			//Librairies Paths
			text : 'lib/require/text',
			domReady : "lib/require/domReady",
			jquery : "http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min",
			Mustache : "lib/mustache"
		}
	});

	require([
		"domReady",
		"Router",
		"routing",
		"jquery"
		],
		function(domReady,Router,routing,$) {
			domReady(function () {
			//loadConfig
			//ImportCSS LETDOOJS
			var r =new Router(routing);

			console.log("testaction");
			$("#event").click(function(){
				r.go("mySecondUrl");
			})
		 });
	});

})();
