// Generated by CoffeeScript 1.5.0
(function() {

	require.config({
		baseUrl:  Environnement.getPath() ,
		paths: {
			//LetDooJs Paths
			Render : "letdoojs/scripts/Render",
			Controller : "letdoojs/scripts/Controller",
			Router : "letdoojs/scripts/Router",
			Process : "letdoojs/scripts/Process",
			routing : "app/routing",

			//Librairies Paths
			domReady : "lib/domReady",
			jquery : "http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min",
			Mustache : "lib/mustache"
		}
	});

	require([
		"domReady",
		"Controller",
		"Router",
		"routing"
		],
		function(domReady,Controller,Router,routing) {

			domReady(function () {
				//loadRoot
				//loadConfig
				//ImportCSS LETDOOJS





			var router = new Router(routing);

			/*
			window.onpopstate = function (event) {
				console.log(event);
			}*/


		 });
	});

})();
